# Generated by Django 4.1.7 on 2023-04-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.IntegerField(default='NULL')),
                ('title', models.CharField(default='NULL', max_length=255)),
                ('parent_id', models.IntegerField(default=0)),
                ('cover_id', models.IntegerField(default='NULL')),
                ('status', models.IntegerField(default=1)),
                ('slug', models.SlugField(default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
