# Generated by Django 4.1.7 on 2023-03-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.IntegerField()),
                ('salt', models.IntegerField()),
                ('status', models.IntegerField(default=1)),
                ('title', models.CharField(default='NULL',max_length=255)),
                ('filename', models.CharField(default='NULL',max_length=255)),
                ('extension', models.CharField(default='NULL', max_length=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
